name: Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-22.04-github-hosted-16core
    container:
      image: matterlabs/zk-environment:latest2.0
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
        echo $(pwd)/bin >> $GITHUB_PATH
        echo IN_DOCKER=1 >> .env
    - run: npm test
